### ISSUE TITLE
HTML special characters are formatted incorrectly

### ISSUE THREAD

**Issue by GenesisTP** [ylambda/noobspike#1]
[See here.](//noobspike.com/#/videos/3iao1c)

It looks like the &lt; in the original title is being formatted as &amp;lt;.

**Comment by plsbrian** [comment]
Thanks! I can try to fix this tonight.

**Comment by ylambda** [comment]
Thanks for finding and reporting this. @TagProKrieger Are you at all familiar with react/flux or interested in it?

**Comment by GenesisTP** [comment]
You know, I didn't want to respond to this earlier because I didn't have a good answer for you at the time, but I'd definitely be interested in helping. I've only barely played around with React and haven't touched Flux at all, but I'm happy to contribute in any way I can. :)

That having been said, I kinda don't want to jump into a new project immediately. I've been spending a ridiculous amount of time on a subreddit CSS update lately, and I'd like to get done with it now for my own sake.

btw why does unfortunatesniper fancy you so much when you clearly put his brother in the sidebar image rotation twice
